### ISSUE TITLE
KeyError "DMODE"

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2109]
Having trouble finding the source of this error message when building the ACME CAM namelist. 

  Running /lcrc/group/earthscience/jacob/ACME3/components/cam/cime_config/buildnml 
Traceback (most recent call last):
  File "./xmlquery", line 365, in <module>
    _main_func()
  File "./xmlquery", line 322, in _main_func
    dtype=dtype, valid_values=valid_values, xmlfile=xmlfile)
  File "./xmlquery", line 262, in xmlquery_sub
    results[group][var]['value'] = value
KeyError: 'DMODE'

Its not a fatal error.   Case continues to setup and build/run sucessfully.

Grep-ing for DMODE turns up nothing except for a substring of AODMODE*

**Comment by jedwards4b** [comment]
what's at line 365 of  /lcrc/group/earthscience/jacob/ACME3/components/cam/cime_config/buildnml?

**Comment by rljacob** [comment]
buildnml only has 223 lines.  Its still in perl.

**Comment by jedwards4b** [comment]
oh - I see, it's in 365 of xmlquery - you need to figure out which xmlquery call in the buildnml is causing the problem.   You can run the buildnml directly from the command line with:
buildnml $caseroot
this may yield more info.

**Comment by sarich** [comment]
I'm getting this too (on blues)

-bash-4.1$ ./xmlquery  DOCN_MODE
Traceback (most recent call last):
  File "./xmlquery", line 365, in <module>
    _main_func()
  File "./xmlquery", line 322, in _main_func
    dtype=dtype, valid_values=valid_values, xmlfile=xmlfile)
  File "./xmlquery", line 262, in xmlquery_sub
    results[group][var]['value'] = value
KeyError: 'DMODE'

**Comment by jgfouca** [comment]
@rljacob , i've hit this before. JimE is correct, this is a problem in one of the ACME perl buildnml scripts.

**Comment by jgfouca** [comment]
@rljacob , you should probably move this ticket to E3SM. You can assign it to me.

**Comment by sarich** [comment]
This is a CIME bug. env_base.py is stripping out the 'OCN_'

**Comment by jedwards4b** [comment]
No - it's a buildnml problem.  There is no variable in cime called OCN_DMODE

**Comment by jedwards4b** [comment]
Oops  - ignore my last - this is a cime bug, I'll take it.

**Comment by jedwards4b** [comment]
What is the compset for this case? In particular what ocn is it?

**Comment by rljacob** [comment]
I see it in a fully coupled case using MPAS.

**Comment by jedwards4b** [comment]
thanks

**Comment by sarich** [comment]
I'm getting the error building cam running --res ne11_oQU240 --compset A_WCYCL1850, but you can recreate with stubs:
```

./create_newcase --case TEST --compset X --res ne30_g16
cd TEST
./xmlquery DOCN_MODE
Traceback (most recent call last):
  File "./xmlquery", line 366, in <module>
    _main_func()
  File "./xmlquery", line 323, in _main_func
    dtype=dtype, valid_values=valid_values, xmlfile=xmlfile)
  File "./xmlquery", line 262, in xmlquery_sub
    results[group][var]['value'] = value
KeyError: 'DMODE'
```

**Comment by jedwards4b** [comment]
I have a fix in
To git@github.com:jedwards4b/cime.git
 * [new branch]      DOCN_MODE_fix -> DOCN_MODE_fix

PR coming soon.

**Comment by jgfouca** [comment]
Thanks @jedwards4b , do you mind adding a quick test for this so we don't regress?

**Comment by jedwards4b** [comment]
will do

**Comment by jgfouca** [comment]
This got fixed by #2114

**Comment by rljacob** [comment]
I'm seeing something related to this again when running case.setup:
```
Creating component namelists
   Running /lcrc/group/earthscience/jacob/ACME3/components/cam/cime_config/buildnml 
ERROR:  No results found for variable DOCN_MODE
```
This is a fully coupled case so there is no DOCN.

**Comment by jedwards4b** [comment]
Is there a DOCN variable in that buildnml file?

**Comment by mvertens** [comment]
Can you please provide us with the create_newcase command you are using.

**Comment by rljacob** [comment]
./create_newcase --case Wcm6brup --res ne30np4_oEC60to30v3_ICG --compset A_WCYCL1850S_CMIP6 --machine anvil

blogin2[102]: grep DOCN buildnml
my $DOCN_MODE		= `./xmlquery  DOCN_MODE		-value`;
    if ($DOCN_MODE eq 'som') {$ocn = "pop";}

**Comment by jedwards4b** [comment]
It's not clear from your post - what buildnml is that?

**Comment by sarich** [comment]
components/cam/cime_config/buildnml

**Comment by jedwards4b** [comment]
I believe that this issue has been resolved in the latest CIME - in particular:
```

**Comment by jedwards4b** [comment]
This is the correct result, you may need to add code to your cam buildnml not to fail in this case.

**Comment by rljacob** [comment]
So remove the "-value" argumenthttps://acme-climate.atlassian.net/wiki/spaces/SE/pages/3244826/Discussion+Pages

**Comment by rljacob** [comment]
Still getting this weird harmless error message:
```
Creating component namelists
   Running /lcrc/group/earthscience/jacob/ACME2/components/cam/cime_config/buildnml 
ERROR:  No results found for variable DOCN_MODE
CAM writing dry deposition namelist to drv_flds_in 
CAM writing namelist to atm_in
```

The case is a fully coupled case: 1850_CAM5%AV1C-L_CLM45%SPBC_MPASCICE%SPUNUP_MPASO%SPUNUP_MOSART_SGLC_SWAV

**Comment by rljacob** [comment]
The case build and runs fine.  Inside the CASEDIR:
```
blogin3[136]: ./xmlquery DOCN_MODE
ERROR:  No results found for variable DOCN_MODE
Exit 1
```
